apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/shipping

patchesStrategicMerge:
  - patches.yaml

images:
  - name: shippingservice
    newName: reg.ayazumman.com/shippingservice
    newTag: dev-latest