apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ad
- cart
- checkout
- currency
- email
- frontend
- loadgenerator
- payment
- productcatalog
- recommendation
- shipping
labels:
- includeSelectors: true
  pairs:
    environment: prod
patches:
- path: patches.yaml
