apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/currency

patchesStrategicMerge:
  - patches.yaml

images:
  - name: currencyservice
    newName: reg.ayazumman.xyz/currencyservice
    newTag: prod-latest