apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/cart
images:
- name: cartservice
  newName: reg.ayazumman.xyz/cartservice
  newTag: prod-latest
patches:
- path: patches.yaml
