---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-proportional-autoscaler
  namespace: emailservice
data:
  linear: |-
    {
      "coresPerReplica": 2,
      "nodesPerReplica": 1,
      "min": 1,
      "max": 10,
      "preventSinglePointFailure": true
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-proportional-autoscaler
  namespace: emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-proportional-autoscaler
  template:
    metadata:
      labels:
        app: cluster-proportional-autoscaler
    spec:
      serviceAccountName: cluster-proportional-autoscaler
      containers:
        - name: cluster-proportional-autoscaler
          image: registry.k8s.io/cpa/cluster-proportional-autoscaler:1.8.6
          args:
            - --configmap=cluster-proportional-autoscaler
            - --logtostderr=true
            - --namespace=emailservice
            - --target=deployment/emailservice
            - --v=2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 200m
              memory: 256Mi
              ephemeral-storage: 2Gi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-proportional-autoscaler
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-proportional-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-proportional-autoscaler
subjects:
  - kind: ServiceAccount
    name: cluster-proportional-autoscaler
    namespace: emailservice
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-proportional-autoscaler
  namespace: emailservice
