apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/productcatalog
images:
- name: productcatalogservice
  newName: reg.ayazumman.xyz/productcatalogservice
  newTag: dev-latest
patches:
- path: patches.yaml
