apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/productcatalog

patchesStrategicMerge:
  - patches.yaml

images:
  - name: productcatalogservice
    newName: reg.ayazumman.com/productcatalogservice
    newTag: prod-latest