apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/loadgenerator

patchesStrategicMerge:
  - patches.yaml

images:
  - name: loadgenerator
    newName: reg.ayazumman.xyz/loadgenerator
    newTag: dev-latest