apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: recommendationservice
  namespace: recommendationservice
spec:
  host: recommendationservice.recommendationservice.svc.cluster.local
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
