# Build
.build:
  stage: build
  image: node:$NODE_VERSION
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week
