apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/cart

patchesStrategicMerge:
  - patches.yaml

images:
  - name: cartservice
    newName: reg.ayazumman.com/cartservice
    newTag: dev-latest