apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/currency
images:
- name: currencyservice
  newName: reg.ayazumman.xyz/currencyservice
  newTag: dev-latest
patches:
- path: patches.yaml
