apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/recommendation

patchesStrategicMerge:
  - patches.yaml

images:
  - name: recommendationservice
    newName: reg.ayazumman.com/recommendationservice
    newTag: dev-latest