apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/recommendation
images:
  - name: recommendationservice
    newName: reg.ayazumman.xyz/recommendationservice
    newTag: dev-latest
