apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/ad
images:
- name: adservice
  newName: reg.ayazumman.xyz/adservice
  newTag: dev-latest
patches:
- path: patches.yaml
