apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: adservice-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: dev
            cluster: https://test-aks-rg-cluster-f7d0tvqb.privatelink.brazilsouth.azmk8s.io:443
            branch: develop
          - env: prod
            cluster: https://aks-rg-cluster-edtpvzbr.privatelink.centralus.azmk8s.io:443
            branch: main
  template:
    metadata:
      name: adservice-{{.env}}
      annotations:
        argocd-image-updater.argoproj.io/image-list: |
          adservice=finalprojectacridtech.azurecr.io/adservice:{{.env}}-*;timestamp
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/write-back-target: kustomization
        argocd-image-updater.argoproj.io/git-branch: "{{.branch}}"
    spec:
      project: boutique
      source:
        repoURL: https://gitlab.ayazumman.xyz/devops/manifests.git
        targetRevision: "{{.branch}}"
        path: overlays/{{.env}}/ad
      destination:
        server: "{{.cluster}}"
        namespace: adservice
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cartservice-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: dev
            cluster: https://test-aks-rg-cluster-f7d0tvqb.privatelink.brazilsouth.azmk8s.io:443
            branch: develop
          - env: prod
            cluster: https://aks-rg-cluster-edtpvzbr.privatelink.centralus.azmk8s.io:443
            branch: main
  template:
    metadata:
      name: cartservice-{{.env}}
      annotations:
        argocd-image-updater.argoproj.io/image-list: |
          cartservice=finalprojectacridtech.azurecr.io/cartservice:{{.env}}-*;timestamp
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/write-back-target: kustomization
        argocd-image-updater.argoproj.io/git-branch: "{{.branch}}"
    spec:
      project: boutique
      source:
        repoURL: https://gitlab.ayazumman.xyz/devops/manifests.git
        targetRevision: "{{.branch}}"
        path: overlays/{{.env}}/cart
      destination:
        server: "{{.cluster}}"
        namespace: cartservice
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: checkoutservice-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: dev
            cluster: https://test-aks-rg-cluster-f7d0tvqb.privatelink.brazilsouth.azmk8s.io:443
            branch: develop
          - env: prod
            cluster: https://aks-rg-cluster-edtpvzbr.privatelink.centralus.azmk8s.io:443
            branch: main
  template:
    metadata:
      name: checkoutservice-{{.env}}
      annotations:
        argocd-image-updater.argoproj.io/image-list: |
          checkoutservice=finalprojectacridtech.azurecr.io/checkoutservice:{{.env}}-*;timestamp
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/write-back-target: kustomization
        argocd-image-updater.argoproj.io/git-branch: "{{.branch}}"
    spec:
      project: boutique
      source:
        repoURL: https://gitlab.ayazumman.xyz/devops/manifests.git
        targetRevision: "{{.branch}}"
        path: overlays/{{.env}}/checkout
      destination:
        server: "{{.cluster}}"
        namespace: checkoutservice
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: currencyservice-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: dev
            cluster: https://test-aks-rg-cluster-f7d0tvqb.privatelink.brazilsouth.azmk8s.io:443
            branch: develop
          - env: prod
            cluster: https://aks-rg-cluster-edtpvzbr.privatelink.centralus.azmk8s.io:443
            branch: main
  template:
    metadata:
      name: currencyservice-{{.env}}
      annotations:
        argocd-image-updater.argoproj.io/image-list: |
          currencyservice=finalprojectacridtech.azurecr.io/currencyservice:{{.env}}-*;timestamp
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/write-back-target: kustomization
        argocd-image-updater.argoproj.io/git-branch: "{{.branch}}"
    spec:
      project: boutique
      source:
        repoURL: https://gitlab.ayazumman.xyz/devops/manifests.git
        targetRevision: "{{.branch}}"
        path: overlays/{{.env}}/currency
      destination:
        server: "{{.cluster}}"
        namespace: currencyservice
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: emailservice-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: dev
            cluster: https://test-aks-rg-cluster-f7d0tvqb.privatelink.brazilsouth.azmk8s.io:443
            branch: develop
          - env: prod
            cluster: https://aks-rg-cluster-edtpvzbr.privatelink.centralus.azmk8s.io:443
            branch: main
  template:
    metadata:
      name: emailservice-{{.env}}
      annotations:
        argocd-image-updater.argoproj.io/image-list: |
          emailservice=finalprojectacridtech.azurecr.io/emailservice:{{.env}}-*;timestamp
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/write-back-target: kustomization
        argocd-image-updater.argoproj.io/git-branch: "{{.branch}}"
    spec:
      project: boutique
      source:
        repoURL: https://gitlab.ayazumman.xyz/devops/manifests.git
        targetRevision: "{{.branch}}"
        path: overlays/{{.env}}/email
      destination:
        server: "{{.cluster}}"
        namespace: emailservice
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: frontend-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: dev
            cluster: https://test-aks-rg-cluster-f7d0tvqb.privatelink.brazilsouth.azmk8s.io:443
            branch: develop
          - env: prod
            cluster: https://aks-rg-cluster-edtpvzbr.privatelink.centralus.azmk8s.io:443
            branch: main
  template:
    metadata:
      name: frontend-{{.env}}
      annotations:
        argocd-image-updater.argoproj.io/image-list: |
          frontend=finalprojectacridtech.azurecr.io/frontend:{{.env}}-*;timestamp
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/write-back-target: kustomization
        argocd-image-updater.argoproj.io/git-branch: "{{.branch}}"
    spec:
      project: boutique
      source:
        repoURL: https://gitlab.ayazumman.xyz/devops/manifests.git
        targetRevision: "{{.branch}}"
        path: overlays/{{.env}}/frontend
      destination:
        server: "{{.cluster}}"
        namespace: frontend
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: loadgenerator-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: dev
            cluster: https://test-aks-rg-cluster-f7d0tvqb.privatelink.brazilsouth.azmk8s.io:443
            branch: develop
          - env: prod
            cluster: https://aks-rg-cluster-edtpvzbr.privatelink.centralus.azmk8s.io:443
            branch: main
  template:
    metadata:
      name: loadgenerator-{{.env}}
      annotations:
        argocd-image-updater.argoproj.io/image-list: |
          loadgenerator=finalprojectacridtech.azurecr.io/loadgenerator:{{.env}}-*;timestamp
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/write-back-target: kustomization
        argocd-image-updater.argoproj.io/git-branch: "{{.branch}}"
    spec:
      project: boutique
      source:
        repoURL: https://gitlab.ayazumman.xyz/devops/manifests.git
        targetRevision: "{{.branch}}"
        path: overlays/{{.env}}/loadgenerator
      destination:
        server: "{{.cluster}}"
        namespace: loadgenerator
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: paymentservice-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: dev
            cluster: https://test-aks-rg-cluster-f7d0tvqb.privatelink.brazilsouth.azmk8s.io:443
            branch: develop
          - env: prod
            cluster: https://aks-rg-cluster-edtpvzbr.privatelink.centralus.azmk8s.io:443
            branch: main
  template:
    metadata:
      name: paymentservice-{{.env}}
      annotations:
        argocd-image-updater.argoproj.io/image-list: |
          paymentservice=finalprojectacridtech.azurecr.io/paymentservice:{{.env}}-*;timestamp
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/write-back-target: kustomization
        argocd-image-updater.argoproj.io/git-branch: "{{.branch}}"
    spec:
      project: boutique
      source:
        repoURL: https://gitlab.ayazumman.xyz/devops/manifests.git
        targetRevision: "{{.branch}}"
        path: overlays/{{.env}}/payment
      destination:
        server: "{{.cluster}}"
        namespace: paymentservice
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: productcatalogservice-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: dev
            cluster: https://test-aks-rg-cluster-f7d0tvqb.privatelink.brazilsouth.azmk8s.io:443
            branch: develop
          - env: prod
            cluster: https://aks-rg-cluster-edtpvzbr.privatelink.centralus.azmk8s.io:443
            branch: main
  template:
    metadata:
      name: productcatalogservice-{{.env}}
      annotations:
        argocd-image-updater.argoproj.io/image-list: |
          productcatalogservice=finalprojectacridtech.azurecr.io/productcatalogservice:{{.env}}-*;timestamp
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/write-back-target: kustomization
        argocd-image-updater.argoproj.io/git-branch: "{{.branch}}"
    spec:
      project: boutique
      source:
        repoURL: https://gitlab.ayazumman.xyz/devops/manifests.git
        targetRevision: "{{.branch}}"
        path: overlays/{{.env}}/productcatalog
      destination:
        server: "{{.cluster}}"
        namespace: productcatalogservice
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: recommendationservice-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: dev
            cluster: https://test-aks-rg-cluster-f7d0tvqb.privatelink.brazilsouth.azmk8s.io:443
            branch: develop
          - env: prod
            cluster: https://aks-rg-cluster-edtpvzbr.privatelink.centralus.azmk8s.io:443
            branch: main
  template:
    metadata:
      name: recommendationservice-{{.env}}
      annotations:
        argocd-image-updater.argoproj.io/image-list: |
          recommendationservice=finalprojectacridtech.azurecr.io/recommendationservice:{{.env}}-*;timestamp
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/write-back-target: kustomization
        argocd-image-updater.argoproj.io/git-branch: "{{.branch}}"
    spec:
      project: boutique
      source:
        repoURL: https://gitlab.ayazumman.xyz/devops/manifests.git
        targetRevision: "{{.branch}}"
        path: overlays/{{.env}}/recommendation
      destination:
        server: "{{.cluster}}"
        namespace: recommendationservice
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: shippingservice-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: dev
            cluster: https://test-aks-rg-cluster-f7d0tvqb.privatelink.brazilsouth.azmk8s.io:443
            branch: develop
          - env: prod
            cluster: https://aks-rg-cluster-edtpvzbr.privatelink.centralus.azmk8s.io:443
            branch: main
  template:
    metadata:
      name: shippingservice-{{.env}}
      annotations:
        argocd-image-updater.argoproj.io/image-list: |
          shippingservice=finalprojectacridtech.azurecr.io/shippingservice:{{.env}}-*;timestamp
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/write-back-target: kustomization
        argocd-image-updater.argoproj.io/git-branch: "{{.branch}}"
    spec:
      project: boutique
      source:
        repoURL: https://gitlab.ayazumman.xyz/devops/manifests.git
        targetRevision: "{{.branch}}"
        path: overlays/{{.env}}/shipping
      destination:
        server: "{{.cluster}}"
        namespace: shippingservice
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
