apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/payment
images:
- name: paymentservice
  newName: reg.ayazumman.xyz/paymentservice
  newTag: prod-latest
patches:
- path: patches.yaml
