apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scaled-object
  namespace: recommendationservice
spec:
  scaleTargetRef:
    name: recommendationservice
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server.monitoring.svc.cluster.local
        metricName: http_requests_total
        query: sum(rate(http_requests_total[1m]))
        threshold: "100"
