apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/frontend
images:
- name: frontend
  newName: reg.ayazumman.xyz/frontend
  newTag: prod-latest
patches:
- path: patches.yaml
