apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/frontend

patchesStrategicMerge:
  - patches.yaml

images:
  - name: frontend
    newName: reg.ayazumman.xyz/frontend
    newTag: prod-latest